// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wms.Infrastructure.Persistence;

#nullable disable

namespace Wms.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WmsDbContext))]
    [Migration("20260827204926_SuppliersAndUnitsFoundation")]
    partial class SuppliersAndUnitsFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("product_internal_code_sequence", "catalog");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claims", "auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims", "auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", "auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", "auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens", "auth");
                });

            modelBuilder.Entity("Wms.Domain.Catalog.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DepthMillimeters")
                        .HasColumnType("integer");

                    b.Property<int?>("HeightMillimeters")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int?>("LengthMillimeters")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_products_category_normalized_name");

                    b.ToTable("products", "catalog");
                });

            modelBuilder.Entity("Wms.Domain.Catalog.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_product_categories_normalized_name");

                    b.ToTable("product_categories", "catalog");
                });

            modelBuilder.Entity("Wms.Domain.Catalog.ProductColor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_product_colors_normalized_name");

                    b.ToTable("product_colors", "catalog");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HexCode = "#808080",
                            IsActive = true,
                            Name = "Cinza",
                            NormalizedName = "CINZA"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HexCode = "#F97316",
                            IsActive = true,
                            Name = "Laranja",
                            NormalizedName = "LARANJA"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HexCode = "#111827",
                            IsActive = true,
                            Name = "Preto",
                            NormalizedName = "PRETO"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HexCode = "#2563EB",
                            IsActive = true,
                            Name = "Azul",
                            NormalizedName = "AZUL"
                        });
                });

            modelBuilder.Entity("Wms.Domain.Catalog.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalBarcode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("InternalCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValueSql("'PV-' || LPAD(nextval('catalog.product_internal_code_sequence')::text, 8, '0')");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalBarcode")
                        .IsUnique()
                        .HasDatabaseName("ux_product_variants_external_barcode")
                        .HasFilter("\"ExternalBarcode\" IS NOT NULL");

                    b.HasIndex("ExternalReference")
                        .HasDatabaseName("ix_product_variants_external_reference");

                    b.HasIndex("InternalCode")
                        .IsUnique()
                        .HasDatabaseName("ux_product_variants_internal_code");

                    b.HasIndex("ProductId");

                    b.ToTable("product_variants", "catalog");
                });

            modelBuilder.Entity("Wms.Domain.Catalog.UnitOfMeasure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_units_of_measure_code");

                    b.ToTable("units_of_measure", "catalog");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            Code = "UN",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Unidade"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            Code = "PAR",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Par"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            Code = "KIT",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Kit / conjunto"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            Code = "KG",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Quilograma"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000005"),
                            Code = "M",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Metro"
                        });
                });

            modelBuilder.Entity("Wms.Domain.Suppliers.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedLegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("TradeName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedLegalName")
                        .HasDatabaseName("ix_suppliers_normalized_legal_name");

                    b.HasIndex("TaxId")
                        .IsUnique()
                        .HasDatabaseName("ux_suppliers_tax_id");

                    b.ToTable("suppliers", "suppliers");
                });

            modelBuilder.Entity("Wms.Infrastructure.Authentication.RefreshSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastUsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReplacedBySessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReplacedBySessionId");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_sessions_token_hash");

                    b.HasIndex("UserId", "ExpiresAtUtc")
                        .HasDatabaseName("ix_refresh_sessions_user_expiration");

                    b.ToTable("refresh_sessions", "auth");
                });

            modelBuilder.Entity("Wms.Infrastructure.Authorization.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_permissions_code");

                    b.HasIndex("Module", "IsActive")
                        .HasDatabaseName("ix_permissions_module_active");

                    b.ToTable("permissions", "auth");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Code = "users.read",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Permite consultar usuários.",
                            IsActive = true,
                            IsSystem = true,
                            Module = "Identity",
                            Name = "Visualizar usuários"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Code = "users.create",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Permite cadastrar novos usuários.",
                            IsActive = true,
                            IsSystem = true,
                            Module = "Identity",
                            Name = "Criar usuários"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Code = "users.update",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Permite alterar dados de usuários.",
                            IsActive = true,
                            IsSystem = true,
                            Module = "Identity",
                            Name = "Atualizar usuários"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Code = "users.disable",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Permite bloquear o acesso de usuários.",
                            IsActive = true,
                            IsSystem = true,
                            Module = "Identity",
                            Name = "Desativar usuários"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Code = "users.roles.manage",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Permite atribuir e remover roles de usuários.",
                            IsActive = true,
                            IsSystem = true,
                            Module = "Identity",
                            Name = "Gerenciar roles de usuários"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Code = "roles.read",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Permite consultar roles e seus acessos.",
                            IsActive = true,
                            IsSystem = true,
                            Module = "Identity",
                            Name = "Visualizar roles"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Code = "roles.manage",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Permite criar e alterar roles e suas permissões.",
                            IsActive = true,
                            IsSystem = true,
                            Module = "Identity",
                            Name = "Gerenciar roles"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            Code = "permissions.read",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Permite consultar o catálogo de permissões.",
                            IsActive = true,
                            IsSystem = true,
                            Module = "Identity",
                            Name = "Visualizar permissões"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            Code = "products.read",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Permite consultar produtos.",
                            IsActive = true,
                            IsSystem = true,
                            Module = "Catalog",
                            Name = "Visualizar produtos"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            Code = "products.create",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Permite cadastrar produtos.",
                            IsActive = true,
                            IsSystem = true,
                            Module = "Catalog",
                            Name = "Criar produtos"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            Code = "products.update",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Permite alterar produtos.",
                            IsActive = true,
                            IsSystem = true,
                            Module = "Catalog",
                            Name = "Atualizar produtos"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            Code = "products.disable",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Permite desativar produtos.",
                            IsActive = true,
                            IsSystem = true,
                            Module = "Catalog",
                            Name = "Desativar produtos"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000013"),
                            Code = "warehouses.read",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Permite consultar armazéns e endereços.",
                            IsActive = true,
                            IsSystem = true,
                            Module = "Warehouse",
                            Name = "Visualizar armazéns"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000014"),
                            Code = "warehouses.manage",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Permite configurar armazéns e endereços.",
                            IsActive = true,
                            IsSystem = true,
                            Module = "Warehouse",
                            Name = "Gerenciar armazéns"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000015"),
                            Code = "inventory.read",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Permite consultar saldos e movimentações.",
                            IsActive = true,
                            IsSystem = true,
                            Module = "Inventory",
                            Name = "Visualizar estoque"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000016"),
                            Code = "inventory.receive",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Permite registrar recebimentos de materiais.",
                            IsActive = true,
                            IsSystem = true,
                            Module = "Inventory",
                            Name = "Receber estoque"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000017"),
                            Code = "inventory.issue",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Permite registrar saídas de materiais.",
                            IsActive = true,
                            IsSystem = true,
                            Module = "Inventory",
                            Name = "Realizar saídas"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000018"),
                            Code = "inventory.transfer",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Permite transferir materiais entre endereços.",
                            IsActive = true,
                            IsSystem = true,
                            Module = "Inventory",
                            Name = "Transferir estoque"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000019"),
                            Code = "inventory.adjust",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Permite executar ajustes controlados de estoque.",
                            IsActive = true,
                            IsSystem = true,
                            Module = "Inventory",
                            Name = "Ajustar estoque"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000020"),
                            Code = "inventory.count",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Permite executar contagens de inventário.",
                            IsActive = true,
                            IsSystem = true,
                            Module = "InventoryCount",
                            Name = "Realizar inventário"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000021"),
                            Code = "suppliers.read",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Permite consultar fornecedores.",
                            IsActive = true,
                            IsSystem = true,
                            Module = "Suppliers",
                            Name = "Visualizar fornecedores"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000022"),
                            Code = "suppliers.manage",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Permite cadastrar e alterar fornecedores.",
                            IsActive = true,
                            IsSystem = true,
                            Module = "Suppliers",
                            Name = "Gerenciar fornecedores"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000023"),
                            Code = "purchasing.read",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Permite consultar processos de compra.",
                            IsActive = true,
                            IsSystem = true,
                            Module = "Purchasing",
                            Name = "Visualizar compras"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000024"),
                            Code = "purchasing.manage",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Permite administrar processos de compra.",
                            IsActive = true,
                            IsSystem = true,
                            Module = "Purchasing",
                            Name = "Gerenciar compras"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000025"),
                            Code = "reports.read",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Permite acessar relatórios e indicadores.",
                            IsActive = true,
                            IsSystem = true,
                            Module = "Analytics",
                            Name = "Visualizar relatórios"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000026"),
                            Code = "audit.read",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Permite consultar registros de auditoria.",
                            IsActive = true,
                            IsSystem = true,
                            Module = "Audit",
                            Name = "Visualizar auditoria"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000027"),
                            Code = "products.delete",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Permite arquivar produtos de forma auditável.",
                            IsActive = true,
                            IsSystem = true,
                            Module = "Catalog",
                            Name = "Excluir produtos"
                        });
                });

            modelBuilder.Entity("Wms.Infrastructure.Authorization.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("AssignedByUserId")
                        .HasDatabaseName("ix_role_permissions_assigned_by_user_id");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions", "auth");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000001"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000002"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000003"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000004"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000005"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000006"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000007"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000008"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000009"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000010"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000011"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000012"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000013"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000014"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000015"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000016"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000017"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000018"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000019"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000020"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000021"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000022"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000023"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000024"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000025"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000026"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000027"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000001"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000009"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000010"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000011"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000012"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000013"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000014"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000015"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000016"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000017"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000018"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000019"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000020"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000021"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000023"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000025"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000026"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000009"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000015"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000021"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000022"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000023"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000024"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000025"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000009"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000013"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000015"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000016"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000017"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000018"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000020"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000005"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000009"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000005"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000013"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000005"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000015"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000005"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000017"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000006"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000009"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000006"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000013"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000006"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000015"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000006"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000020"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000006"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000025"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = new Guid("20000000-0000-0000-0000-000000000006"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000026"),
                            AssignedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Wms.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", "auth");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            ConcurrencyStamp = "system-role-20000000000000000000000000000001",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Administrador do sistema com acesso a todas as permissões.",
                            IsSystem = true,
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            ConcurrencyStamp = "system-role-20000000000000000000000000000002",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Gestor responsável pela administração operacional do estoque.",
                            IsSystem = true,
                            Name = "WarehouseManager",
                            NormalizedName = "WAREHOUSEMANAGER"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            ConcurrencyStamp = "system-role-20000000000000000000000000000003",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Responsável por fornecedores e processos de compra.",
                            IsSystem = true,
                            Name = "Buyer",
                            NormalizedName = "BUYER"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            ConcurrencyStamp = "system-role-20000000000000000000000000000004",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Responsável pelas movimentações físicas do estoque.",
                            IsSystem = true,
                            Name = "StockKeeper",
                            NormalizedName = "STOCKKEEPER"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            ConcurrencyStamp = "system-role-20000000000000000000000000000005",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Responsável pela separação e expedição de materiais.",
                            IsSystem = true,
                            Name = "Picker",
                            NormalizedName = "PICKER"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            ConcurrencyStamp = "system-role-20000000000000000000000000000006",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Responsável por inventários e auditoria operacional.",
                            IsSystem = true,
                            Name = "Auditor",
                            NormalizedName = "AUDITOR"
                        });
                });

            modelBuilder.Entity("Wms.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_email");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", "auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Wms.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Wms.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Wms.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Wms.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wms.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Wms.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wms.Domain.Catalog.Product", b =>
                {
                    b.HasOne("Wms.Domain.Catalog.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Wms.Domain.Catalog.ProductVariant", b =>
                {
                    b.HasOne("Wms.Domain.Catalog.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Wms.Infrastructure.Authentication.RefreshSession", b =>
                {
                    b.HasOne("Wms.Infrastructure.Authentication.RefreshSession", "ReplacedBySession")
                        .WithMany()
                        .HasForeignKey("ReplacedBySessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Wms.Infrastructure.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReplacedBySession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Wms.Infrastructure.Authorization.RolePermission", b =>
                {
                    b.HasOne("Wms.Infrastructure.Identity.ApplicationUser", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Wms.Infrastructure.Authorization.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wms.Infrastructure.Identity.ApplicationRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Wms.Domain.Catalog.Product", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Wms.Domain.Catalog.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Wms.Infrastructure.Authorization.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Wms.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
